name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Echo A Secret
      run: |
        echo $SECRET1
      env:
        SECRET1: ${{secrets.SECRET1}}
    - name: Echo A Secret elaborate
      run: ./echo_SECRET1.sh
      env:
        SECRET1: ${{secrets.SECRET1}}
